version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:7.0
    container_name: ai-archaeology-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ai-archaeology-archive
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ai-archaeology-network

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-archaeology-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ai-archaeology-archive?authSource=admin
      CORS_ORIGIN: http://localhost:4002
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ai-archaeology-network

  # 前端应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-archaeology-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4001/api
    ports:
      - "4002:4002"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ai-archaeology-network

volumes:
  mongodb_data:

networks:
  ai-archaeology-network:
    driver: bridge
